### ISSUE TITLE
Add a way to inject config to data nodes

### ISSUE THREAD

**Issue by surjikal** [postmind-net/pgxl-docker#2]
It would be interesting to add a way to append some configuration variables to the datanode's `postgresql.conf`. Right now, you have to edit them all manually.

I can submit a patch when I have more time.

**Comment by lmatthieu** [comment]
Hi !

Thank you for you feedback, you can append configuration variables to the datanode's by putting the file node.conf in the pgxc_ctl directory. You have an example in the directory pom/pgxc_ctl.
